_BASE_: ../maskformer2_R50_bs16_50ep.yaml
MODEL:
  BACKBONE:
    NAME: "DinoV2"
  DINOV2:

  SWIN:
    EMBED_DIM: 768
    DEPTHS: 12
    NUM_HEADS: 12
    WINDOW_SIZE: 16
    WINDOW_BLOCK_INDEXES: [0, 1, 3, 4, 6, 7, 9, 10,]
    USE_CHECKPOINT: True
    OUT_CHANNLE: 256
    SCALE_FACTORS: [4.0, 2.0, 1.0, 0.5]
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]


  # WEIGHTS: "swin_base_patch4_window12_384.pkl"
  # WEIGHTS: "/home/yangzhen/checkpoints/segmentation/dinov2_vits14_pretrain.pth"
  WEIGHTS: "/home/yangzhen/checkpoints/segmentation/new_dinov2_vitb14_pretrain.pth"
  # WEIGHTS: "/home/yangzhen/checkpoints/segmentation/model_final_f6e0f6.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  # TODO
  
